/* RBORACLE7A: physical-write oracle for Leica ASMRedBlueInterpolation1.
 *
 * Exact routine ABI is inherited from interp1_oracle_parametric.s.
 * WIDTH, HEIGHT, SUPPORT_INIT, GREEN_PTR, OUTA_PTR, OUTB_PTR are supplied
 * with --defsym.  All four data/output sections contain deterministic random
 * u16 values generated by CI.  Unlike the older oracle, this harness dumps
 * the ENTIRE output windows starting at 0x6000/0x7000 so pre-pointer guard,
 * formal image, and tail writes are all observable.
 */
    .equ DUMP_DWORDS, 512

    .section .text.start,"ax"
    .global _start
    .type _start, STT_FUNC
_start:
    SP.H = 0x0000; SP.L = 0x9800; SP += -0x1c;

    /* arg0: signed16 difference plane; old validated public base 0x4040 */
    R0.H = 0x0000; R0.L = 0x4040;
    /* arg1: 14-bit green plane, caller phase supplied per support_after */
    R1.H = 0x0000; R1.L = GREEN_PTR;
    /* arg2: output A */
    R2.H = 0x0000; R2.L = OUTA_PTR;
    /* arg3: output B */
    R3.H = 0x0000; R3.L = OUTB_PTR; [SP + 0x0c] = R3;
    /* arg4/5: width and height */
    R3 = WIDTH (Z); [SP + 0x10] = R3;
    R3 = HEIGHT (Z); [SP + 0x14] = R3;
    /* arg6: mutable support integer */
    R3.H = 0x0000; R3.L = 0x8000; [SP + 0x18] = R3;

    CALL leica_interp1;
    SP += 0x1c;

    /* First DBG word is support_after. */
    P0.H = 0x0000; P0.L = 0x8000; R0 = [P0]; DBG R0;

    /* Then 1024 u16 / 512 dwords for output A from section base. */
    P0.H = 0x0000; P0.L = 0x6000;
    .rept DUMP_DWORDS
      R0 = [P0++]; DBG R0;
    .endr

    /* Then 1024 u16 / 512 dwords for output B from section base. */
    P0.H = 0x0000; P0.L = 0x7000;
    .rept DUMP_DWORDS
      R0 = [P0++]; DBG R0;
    .endr

    HLT;
    .size _start, .-_start

    .balign 4
    .global leica_interp1
leica_interp1:
    .incbin "ASMRedBlueInterpolation1.bin"

    .section .oracle_diff,"aw"
    .balign 4
    .include "oracle_diff_data.inc"

    .section .oracle_green,"aw"
    .balign 4
    .include "oracle_green_data.inc"

    .section .oracle_outa,"aw"
    .balign 4
    .include "oracle_outa_data.inc"

    .section .oracle_outb,"aw"
    .balign 4
    .include "oracle_outb_data.inc"

    .section .oracle_border,"aw"
    .balign 4
    .long SUPPORT_INIT

    .section .oracle_stack,"aw"
    .balign 4
    .space 0x1000
