#!/usr/bin/env python3
from pathlib import Path
import sys
ROOT=Path(sys.argv[1]) if len(sys.argv)>1 else Path('PhotonCamera')
R=ROOT/'app/src/main/java/com/particlesdevs/photoncamera/m9/render/M9R35Renderer.java'; C=ROOT/'app/src/main/java/com/particlesdevs/photoncamera/m9/render/M9NativeColorCore.java'; CPP=ROOT/'app/src/main/cpp/m9color_jni.cpp'; B=ROOT/'app/build.gradle'
for p in (R,C,CPP,B):
    if not p.exists(): raise SystemExit('NEUTRAL1A missing '+str(p))
def rep(s,a,b,n):
    c=s.count(a)
    if c!=1: raise SystemExit(f'NEUTRAL1A {n} anchor count={c}')
    return s.replace(a,b,1)
def mend(s,mark):
    st=s.index(mark); br=s.index('{',st); d=0
    for i in range(br,len(s)):
        if s[i]=='{': d+=1
        elif s[i]=='}':
            d-=1
            if d==0:return i+1
    raise SystemExit('unterminated '+mark)
r=R.read_text(); c=C.read_text(); cpp=CPP.read_text(); b=B.read_text()

# Extend existing MHC JNI with neutral-aware mode; false remains bit-identical plain MHC.
c=rep(c,'''    static native long demosaicMhcRggb(short[] raw,\n                                       int width,\n                                       int height,\n                                       java.nio.ByteBuffer outRgb16,\n                                       int workers,\n                                       long[] stats);''','''    static native long demosaicMhcRggb(short[] raw,\n                                       int width,\n                                       int height,\n                                       java.nio.ByteBuffer outRgb16,\n                                       int workers,\n                                       float neutralR, float neutralG, float neutralB,\n                                       boolean neutralAware,\n                                       long[] stats);''','java JNI')

# Neutral-balanced 5x5 MHC. CFA samples are never pre-scaled/clipped; sampled output sites stay exact.
mark='inline void mhcPixelRggb(const jshort* raw, int width, int height,\n                         int y, int x, uint16_t* rgb) {'
e=mend(cpp,mark)
h=r'''\n\ninline double mhcNAt(const jshort* raw,int w,int h,int y,int x,double ir,double ig,double ib){\n    y=mhcClampCoord(y,h); x=mhcClampCoord(x,w);\n    double k=((y&1)==0&&(x&1)==0)?ir:(((y&1)!=0&&(x&1)!=0)?ib:ig);\n    return static_cast<double>(u16(raw[y*w+x]))*k;\n}\ninline uint16_t mhcND(double v){\n    if(!std::isfinite(v)||v<=0.0)return 0; if(v>=65535.0)return 65535; return static_cast<uint16_t>(std::llround(v));\n}\ninline void mhcPixelNeutralRggb(const jshort* raw,int w,int h,int y,int x,uint16_t* rgb,double nr,double nb,double ir,double ib){\n    const double ig=1.0;\n    const double C=mhcNAt(raw,w,h,y,x,ir,ig,ib),N=mhcNAt(raw,w,h,y-1,x,ir,ig,ib),S=mhcNAt(raw,w,h,y+1,x,ir,ig,ib),W=mhcNAt(raw,w,h,y,x-1,ir,ig,ib),E=mhcNAt(raw,w,h,y,x+1,ir,ig,ib);\n    const double NN=mhcNAt(raw,w,h,y-2,x,ir,ig,ib),SS=mhcNAt(raw,w,h,y+2,x,ir,ig,ib),WW=mhcNAt(raw,w,h,y,x-2,ir,ig,ib),EE=mhcNAt(raw,w,h,y,x+2,ir,ig,ib);\n    const double NW=mhcNAt(raw,w,h,y-1,x-1,ir,ig,ib),NE=mhcNAt(raw,w,h,y-1,x+1,ir,ig,ib),SW=mhcNAt(raw,w,h,y+1,x-1,ir,ig,ib),SE=mhcNAt(raw,w,h,y+1,x+1,ir,ig,ib);\n    const double g=(4*C+2*(N+S+W+E)-(NN+SS+WW+EE))/8.0;\n    const double o=(12*C+4*(NW+NE+SW+SE)-3*(NN+SS+WW+EE))/16.0;\n    const double hh=(10*C+8*(W+E)+(NN+SS)-2*(NW+NE+SW+SE)-2*(WW+EE))/16.0;\n    const double vv=(10*C+8*(N+S)+(WW+EE)-2*(NW+NE+SW+SE)-2*(NN+SS))/16.0;\n    const bool ey=(y&1)==0,ex=(x&1)==0; const uint16_t sm=u16(raw[y*w+x]);\n    if(ey&&ex){rgb[0]=sm;rgb[1]=mhcND(g);rgb[2]=mhcND(o*nb);}\n    else if(!ey&&!ex){rgb[0]=mhcND(o*nr);rgb[1]=mhcND(g);rgb[2]=sm;}\n    else if(ey){rgb[0]=mhcND(hh*nr);rgb[1]=sm;rgb[2]=mhcND(vv*nb);}\n    else{rgb[0]=mhcND(vv*nr);rgb[1]=sm;rgb[2]=mhcND(hh*nb);}\n}\n'''.replace('\\n','\n')
if 'mhcPixelNeutralRggb(' not in cpp: cpp=cpp[:e]+h+cpp[e:]

cpp=rep(cpp,'''        jobject outBuffer,\n        jint workers,\n        jlongArray statsArray) {''','''        jobject outBuffer,\n        jint workers,\n        jfloat neutralR, jfloat neutralG, jfloat neutralB,\n        jboolean neutralAware,\n        jlongArray statsArray) {''','jni signature')
cpp=rep(cpp,'''    if (!rawArray || !outBuffer || width <= 0 || height <= 0) return -1;\n    const int64_t pixels64''','''    if (!rawArray || !outBuffer || width <= 0 || height <= 0) return -1;\n    if (neutralAware && (!std::isfinite(neutralR)||!std::isfinite(neutralG)||!std::isfinite(neutralB)||neutralR<=0||neutralG<=0||neutralB<=0)) return -6;\n    const double nr=neutralAware?static_cast<double>(neutralR)/static_cast<double>(neutralG):1.0;\n    const double nb=neutralAware?static_cast<double>(neutralB)/static_cast<double>(neutralG):1.0;\n    if(!std::isfinite(nr)||!std::isfinite(nb)||nr<=0.0||nb<=0.0)return -7;\n    const double invR=1.0/nr,invB=1.0/nb;\n    const int64_t pixels64''','jni neutral setup')
cpp=rep(cpp,'''                    mhcPixelRggb(raw, width, height, y, x,\n                                 out + (static_cast<size_t>(y) * static_cast<size_t>(width)\n                                        + static_cast<size_t>(x)) * 3u);''','''                    uint16_t* dst=out+(static_cast<size_t>(y)*static_cast<size_t>(width)+static_cast<size_t>(x))*3u;\n                    if(neutralAware) mhcPixelNeutralRggb(raw,width,height,y,x,dst,nr,nb,invR,invB);\n                    else mhcPixelRggb(raw,width,height,y,x,dst);''','jni loop')

# Same-RAW three-way bank. Candidate self-meters; both controls use its exact effective gain.
r=rep(r,'''                        String[] suffixes = {\n                                "_DEMOSAICAB_MHC_SAT3",\n                                "_DEMOSAICAB_EA_SAT3_GAINLOCK"\n                        };''','''                        String[] suffixes = {\n                                "_DEMOSAICNEUTRAL_MHCNB_SAT3",\n                                "_DEMOSAICNEUTRAL_MHCPLAIN_SAT3_GAINLOCK",\n                                "_DEMOSAICNEUTRAL_EA_SAT3_GAINLOCK"\n                        };''','suffixes')
r=rep(r,'''                        String[] bridgeProbeNames = {\n                                "demosaicab_mhc_sat3_control",\n                                "demosaicab_ea_sat3_gainlocked"\n                        };''','''                        String[] bridgeProbeNames = {\n                                "demosaicneutral_mhcnb_sat3_control",\n                                "demosaicneutral_mhcplain_sat3_gainlocked",\n                                "demosaicneutral_ea_sat3_gainlocked"\n                        };''','names')
for a,z,n in [
('int[] bridgeProbeModes = {50, 54};','int[] bridgeProbeModes = {50, 55, 54};','modes'),('boolean[] selfMeterFlags = {true, false};','boolean[] selfMeterFlags = {true, false, false};','meter'),('double[] hsmValueStrengthFlags = {1.0, 1.0};','double[] hsmValueStrengthFlags = {1.0, 1.0, 1.0};','hsm'),('boolean[] applyShadingFlags = {true, true};','boolean[] applyShadingFlags = {true, true, true};','shade'),('boolean[] applyShadedGuard1AFlags = {false, false};','boolean[] applyShadedGuard1AFlags = {false, false, false};','guard'),('boolean[] applyShadedGuardCap20Ev1AFlags = {false, false};','boolean[] applyShadedGuardCap20Ev1AFlags = {false, false, false};','guardcap'),('boolean[] applyShadingLumaDecomp1AFlags = {true, true};','boolean[] applyShadingLumaDecomp1AFlags = {true, true, true};','decomp'),('double[] shadingLumaAuthorityAlphaFlags = {1.0, 1.0};','double[] shadingLumaAuthorityAlphaFlags = {1.0, 1.0, 1.0};','alpha'),('boolean[] normalizeShadingLumaOutsideMedian1AFlags = {true, true};','boolean[] normalizeShadingLumaOutsideMedian1AFlags = {true, true, true};','norm'),('double[] shadingLumaTargetOutsideMedianEv1AFlags = {0.30, 0.30};','double[] shadingLumaTargetOutsideMedianEv1AFlags = {0.30, 0.30, 0.30};','target')]: r=rep(r,a,z,n)

r=rep(r,'final boolean demosaicAbEaRequested1A = bridgeProbeMode == 54;','final boolean demosaicNeutralEa1A = bridgeProbeMode == 54;\n        final boolean demosaicPlainMhc1A = bridgeProbeMode == 55;','flags')
r=r.replace('demosaicAbEaRequested1A','demosaicNeutralEa1A')
r=rep(r,'''            } else {\n                long mhcNativeNs = M9NativeColorCore.demosaicMhcRggb(\n                        norm16, width, height, mhcRgbBuffer, NATIVE_COLOR_WORKERS, mhcStats);\n                if (mhcNativeNs < 0) {\n                    throw new IllegalStateException("DEMOSAICMHC1A native failure: " + mhcNativeNs);\n                }\n            }''','''            } else {\n                long mhcNativeNs = M9NativeColorCore.demosaicMhcRggb(\n                        norm16,width,height,mhcRgbBuffer,NATIVE_COLOR_WORKERS,\n                        neutralF[0],neutralF[1],neutralF[2],!demosaicPlainMhc1A,mhcStats);\n                if(mhcNativeNs<0) throw new IllegalStateException("DEMOSAICMHCNEUTRAL1A native failure: "+mhcNativeNs);\n            }''','call')
r=rep(r,'skySatDiagnosticEncoded1A = bridgeProbeMode >= 50 && bridgeProbeMode <= 54','skySatDiagnosticEncoded1A = bridgeProbeMode >= 50 && bridgeProbeMode <= 55','range')
# Replace telemetry labels; retain existing timing/lifetime mechanics.
r=r.replace('DEMOSAICAB1A_OpenCV_COLOR_BayerRG2BGR_EA_sameRAW_gainlocked','DEMOSAICMHCNEUTRAL1A_OpenCV_EA_sameRAW_gainlocked')
r=r.replace('DEMOSAICMHC1A_MalvarHeCutler5x5_RGGB_native_direct','DEMOSAICMHCNEUTRAL1A_MalvarHeCutler5x5_RGGB_liveNeutral_balanced_restore')
r=r.replace('demosaicAb1A','demosaicMhcNeutral1A').replace('demosaicAbVariant','demosaicNeutralVariant').replace('demosaicAbSameRawBayer','demosaicNeutralSameRawBayer').replace('demosaicAbOnlyPhotographicDifference','demosaicNeutralOnlyPhotographicDifference').replace('demosaicAbDownstreamFrozen','demosaicNeutralDownstreamFrozen')
r=rep(r,'''            d.put("demosaicNeutralVariant", demosaicNeutralEa1A\n                    ? "EA_SAT3_GAINLOCK" : "MHC_SAT3_CONTROL");''','''            d.put("demosaicNeutralVariant", demosaicNeutralEa1A ? "EA_SAT3_GAINLOCK" : (demosaicPlainMhc1A ? "MHC_PLAIN_SAT3_GAINLOCK" : "MHC_NEUTRAL_SAT3_CONTROL"));\n            d.put("demosaicNeutralR",neutralF[0]); d.put("demosaicNeutralG",neutralF[1]); d.put("demosaicNeutralB",neutralF[2]);\n            d.put("demosaicNeutralIntermediateClipping",false);\n            d.put("demosaicNeutralSourceTransformOwnership","interpolation_geometry_only_SOURCECAL2A_owns_color_transform");''','telemetry')
r=rep(r,'''            d.put("demosaicMode", demosaicNeutralEa1A\n                    ? "DEMOSAICMHCNEUTRAL1A_OpenCV_EA_sameRAW_gainlocked"\n                    : "DEMOSAICMHCNEUTRAL1A_MalvarHeCutler5x5_RGGB_liveNeutral_balanced_restore");''','''            d.put("demosaicMode", demosaicNeutralEa1A ? "DEMOSAICMHCNEUTRAL1A_OpenCV_EA_sameRAW_gainlocked" : (demosaicPlainMhc1A ? "DEMOSAICMHC1A_MalvarHeCutler5x5_RGGB_plain_sameRAW_gainlocked" : "DEMOSAICMHCNEUTRAL1A_MalvarHeCutler5x5_RGGB_liveNeutral_balanced_restore"));''','mode telemetry')
r=r.replace('demosaicNeutralOnlyPhotographicDifference", "demosaic_kernel"','demosaicNeutralOnlyPhotographicDifference", "demosaic_interpolation_domain_kernel"')
r=rep(r,'"legacy_OpenCV_EA_available_as_mode54_sameRAW_control"','demosaicPlainMhc1A ? "active_sameRAW_plain_MHC_gainlocked_control" : "production_candidate_liveNeutral_balanced_MHC"','control telemetry')
if b.count('-demosaicmhc1a-demosaicab1a')!=1: raise SystemExit('version anchor')
b=b.replace('-demosaicmhc1a-demosaicab1a','-demosaicmhc1a-demosaicab1a-demosaicmhcneutral1a',1)
R.write_text(r); C.write_text(c); CPP.write_text(cpp); B.write_text(b)
print('DEMOSAICMHCNEUTRAL1A applied: neutral MHC primary + plain MHC/EA gainlocked controls; downstream frozen')
